/**
 * 20 synthetic mentor personas for dev seeding.
 * All use password: devpass123
 * All emails: mentor.FIRSTNAME@bandb.test
 *
 * Area names must exactly match the MENTORSHIP_AREAS constant in MentorApply.jsx.
 */

export const DEV_MENTORS = [

  // ── 1 ─────────────────────────────────────────────────────────────────────
  {
    email:    'mentor.marcus@bandb.test',
    password: 'devpass123',
    profile: {
      name:              'Marcus Thompson',
      hometown:          'Columbus',
      state:             'OH',
      gender:            'Male',
      ethnicity:         'Black / African American',
      sport:             'Football',
      college:           'Ohio State University',
      division:          'D1',
      years_active:      4,
      position:          'Wide Receiver',
      career_highlights: 'Two-time Big Ten champion · 124 career receptions · Honorable mention All-Big Ten',
      major:             'Sports Management',
      gpa_range:         '3.0–3.5',
      graduate_school:   null,
      current_job:       'Player Personnel Analyst',
      current_employer:  'NFL Front Office',
      industry:          'Sports / Athletics',
      current_city:      'Cleveland',
      current_state:     'OH',
      bio: `I played wide receiver at Ohio State for four years, finishing with 124 career receptions and two Big Ten championships. Balancing intense film study, strength training, and a full course load taught me more about discipline than anything else. After going undrafted, I transitioned to the business side of football and now work as a player personnel analyst for an NFL franchise. I'm passionate about helping young athletes use their platform wisely—especially around NIL opportunities—and understanding what elite D1 performance demands on and off the field.`,
    },
    areas: [
      { category: 'Athletic Development',  area: 'Sport-Specific Skills' },
      { category: 'Athletic Development',  area: 'Film Study' },
      { category: 'Athletic Development',  area: 'Mental Performance' },
      { category: 'Career & Life Skills',  area: 'NIL Guidance' },
      { category: 'Career & Life Skills',  area: 'Career Exploration' },
    ],
    availability: { hours_per_week: 3, format: 'Video Call', timezone: 'America/New_York' },
  },

  // ── 2 ─────────────────────────────────────────────────────────────────────
  {
    email:    'mentor.keisha@bandb.test',
    password: 'devpass123',
    profile: {
      name:              'Keisha Williams',
      hometown:          'Hartford',
      state:             'CT',
      gender:            'Female',
      ethnicity:         'Black / African American',
      sport:             'Basketball',
      college:           'University of Connecticut',
      division:          'D1',
      years_active:      4,
      position:          'Point Guard',
      career_highlights: 'Two Final Four appearances · Two-time All-Big East · Team captain senior year',
      major:             'Psychology',
      gpa_range:         '3.5–4.0',
      graduate_school:   'Teachers College, Columbia University — M.Ed.',
      current_job:       'Graduate Student & Head Coach',
      current_employer:  'Bronx High School Basketball',
      industry:          'Education',
      current_city:      'New York',
      current_state:     'NY',
      bio: `I ran point guard at UConn for four years, reaching two Final Fours and earning two All-Big East selections. Managing academics alongside one of the top programs in the country was relentless—I learned to prioritize, study in short windows, and lean on my teammates. I'm now earning my master's in education at Columbia while coaching high school basketball in the Bronx. I love working with athletes who want to dominate in the classroom as much as on the court, and I'm especially committed to mentoring girls navigating the college recruiting process.`,
    },
    areas: [
      { category: 'Athletic Development',  area: 'Sport-Specific Skills' },
      { category: 'Athletic Development',  area: 'Mental Performance' },
      { category: 'Career & Life Skills',  area: 'Time Management' },
      { category: 'Test Prep & Advising',  area: 'College Selection' },
      { category: 'Test Prep & Advising',  area: 'College Essays' },
    ],
    availability: { hours_per_week: 3, format: 'Video Call', timezone: 'America/New_York' },
  },

  // ── 3 ─────────────────────────────────────────────────────────────────────
  {
    email:    'mentor.sofia@bandb.test',
    password: 'devpass123',
    profile: {
      name:              'Sofia Reyes',
      hometown:          'San Antonio',
      state:             'TX',
      gender:            'Female',
      ethnicity:         'Hispanic / Latino',
      sport:             'Soccer',
      college:           'UCLA',
      division:          'D1',
      years_active:      4,
      position:          'Midfielder',
      career_highlights: 'NCAA quarterfinal · Academic All-American · Full athletic scholarship',
      major:             'Kinesiology',
      gpa_range:         '3.5–4.0',
      graduate_school:   'USC — Doctor of Physical Therapy (in progress)',
      current_job:       'DPT Student & Volunteer Assistant Coach',
      current_employer:  'USC Keck School of Medicine',
      industry:          'Healthcare',
      current_city:      'Los Angeles',
      current_state:     'CA',
      bio: `I played midfielder at UCLA on a full athletic scholarship, reaching the NCAA quarterfinals my sophomore year. My kinesiology major gave me a deep understanding of how the body performs and breaks down, and I became obsessed with injury prevention. I'm now in my second year of a Doctor of Physical Therapy program at USC. I help athletes train smarter, recover properly, and stay healthy over a long career. I'm especially passionate about supporting Latina athletes navigating the dual demands of a D1 scholarship and a competitive major.`,
    },
    areas: [
      { category: 'Athletic Development', area: 'Athletic Training' },
      { category: 'Athletic Development', area: 'Nutrition' },
      { category: 'Athletic Development', area: 'Strength & Conditioning' },
      { category: 'Athletic Development', area: 'Sport-Specific Skills' },
    ],
    availability: { hours_per_week: 3, format: 'Any', timezone: 'America/Los_Angeles' },
  },

  // ── 4 ─────────────────────────────────────────────────────────────────────
  {
    email:    'mentor.devon@bandb.test',
    password: 'devpass123',
    profile: {
      name:              'Devon Carter',
      hometown:          'Richmond',
      state:             'VA',
      gender:            'Male',
      ethnicity:         'Black / African American',
      sport:             'Football',
      college:           'Hampton University',
      division:          'D2',
      years_active:      4,
      position:          'Linebacker',
      career_highlights: 'Three-time MEAC All-Conference · Team captain · Graduated with honors',
      major:             'Business Administration',
      gpa_range:         '3.5–4.0',
      graduate_school:   null,
      current_job:       'Financial Advisor',
      current_employer:  'Edward Jones',
      industry:          'Finance',
      current_city:      'Richmond',
      current_state:     'VA',
      bio: `I played linebacker at Hampton University, an HBCU where competing without the D1 spotlight taught me to earn everything. What Hampton gave me beyond football was community, a powerful network, and a sense of identity I carry every day. I studied business administration and graduated with honors, then went straight into financial services. Today I'm a licensed financial advisor helping families build generational wealth. I'm deeply committed to mentoring athletes on financial literacy, NIL money, and scholarships—tools most players don't know exist until it's too late.`,
    },
    areas: [
      { category: 'Career & Life Skills',  area: 'Financial Literacy' },
      { category: 'Career & Life Skills',  area: 'NIL Guidance' },
      { category: 'Career & Life Skills',  area: 'Career Exploration' },
      { category: 'Career & Life Skills',  area: 'Resume / Interview Prep' },
      { category: 'Test Prep & Advising',  area: 'Financial Aid / Scholarships' },
    ],
    availability: { hours_per_week: 3, format: 'Video Call', timezone: 'America/New_York' },
  },

  // ── 5 ─────────────────────────────────────────────────────────────────────
  {
    email:    'mentor.amara@bandb.test',
    password: 'devpass123',
    profile: {
      name:              'Amara Osei',
      hometown:          'Atlanta',
      state:             'GA',
      gender:            'Female',
      ethnicity:         'Black / African American',
      sport:             'Track & Field',
      college:           'University of Texas at Austin',
      division:          'D1',
      years_active:      4,
      position:          '100m / 200m Sprinter',
      career_highlights: 'Three-time All-American · Big 12 200m relay champion · Nike-sponsored athlete post-graduation',
      major:             'Communications',
      gpa_range:         '3.0–3.5',
      graduate_school:   null,
      current_job:       'Sports Marketing Manager',
      current_employer:  'Nike',
      industry:          'Entertainment / Media',
      current_city:      'Portland',
      current_state:     'OR',
      bio: `I ran the 100m and 200m at the University of Texas, earning three All-American honors and a Big 12 relay championship. Track taught me what it means to peak at exactly the right moment—physically and mentally. I majored in communications and now work in sports marketing at Nike, helping athletes build their personal brands. I love mentoring young female athletes on NIL strategy, career planning in sport business, and the nutrition and mental performance side of sprinting.`,
    },
    areas: [
      { category: 'Athletic Development', area: 'Nutrition' },
      { category: 'Athletic Development', area: 'Mental Performance' },
      { category: 'Athletic Development', area: 'Strength & Conditioning' },
      { category: 'Career & Life Skills', area: 'NIL Guidance' },
      { category: 'Career & Life Skills', area: 'Career Exploration' },
    ],
    availability: { hours_per_week: 1, format: 'Video Call', timezone: 'America/Chicago' },
  },

  // ── 6 ─────────────────────────────────────────────────────────────────────
  {
    email:    'mentor.emma@bandb.test',
    password: 'devpass123',
    profile: {
      name:              'Emma Schultz',
      hometown:          'Minneapolis',
      state:             'MN',
      gender:            'Female',
      ethnicity:         'White / Caucasian',
      sport:             'Swimming',
      college:           'Williams College',
      division:          'D3',
      years_active:      4,
      position:          'Freestyle / Butterfly',
      career_highlights: 'Two-time NESCAC champion (100 fly) · Academic All-American · 3.92 GPA',
      major:             'Biology',
      gpa_range:         '3.5–4.0',
      graduate_school:   'Harvard Medical School — MD (in progress)',
      current_job:       'Medical Student',
      current_employer:  'Harvard Medical School',
      industry:          'Healthcare',
      current_city:      'Boston',
      current_state:     'MA',
      bio: `I swam at Williams College, a Division III school where I discovered you can pursue elite athletics and serious academics without sacrificing either. I was a two-time NESCAC champion in the 100 butterfly and graduated with a 3.92 GPA in biology. I'm now a second-year medical student at Harvard. Choosing D3 over D1 offers was the best decision I ever made, and I want to help athletes understand all the paths available to them. I'm especially strong at helping students with STEM coursework, test prep, and thinking through college fit.`,
    },
    areas: [
      { category: 'Academic',             area: 'Sciences' },
      { category: 'Academic',             area: 'Mathematics' },
      { category: 'Test Prep & Advising', area: 'SAT / ACT Prep' },
      { category: 'Test Prep & Advising', area: 'College Essays' },
      { category: 'Test Prep & Advising', area: 'College Selection' },
      { category: 'Career & Life Skills', area: 'Time Management' },
    ],
    availability: { hours_per_week: 1, format: 'Video Call', timezone: 'America/New_York' },
  },

  // ── 7 ─────────────────────────────────────────────────────────────────────
  {
    email:    'mentor.alejandro@bandb.test',
    password: 'devpass123',
    profile: {
      name:              'Alejandro Vega',
      hometown:          'Chicago',
      state:             'IL',
      gender:            'Male',
      ethnicity:         'Hispanic / Latino',
      sport:             'Soccer',
      college:           'University of Saint Francis',
      division:          'NAIA',
      years_active:      4,
      position:          'Striker',
      career_highlights: 'Two-time NAIA All-American · Scored 38 career goals · Academic All-Conference',
      major:             'Mechanical Engineering',
      gpa_range:         '3.5–4.0',
      graduate_school:   null,
      current_job:       'Product Engineer',
      current_employer:  'Invenergy',
      industry:          'Technology',
      current_city:      'Chicago',
      current_state:     'IL',
      bio: `I played striker at the University of Saint Francis in Indiana on a partial soccer scholarship. Going NAIA instead of chasing a D2 offer gave me room to study engineering without an overwhelming travel schedule—and I thrived, finishing with a 3.8 GPA. I was a two-time NAIA All-American and now work as a product engineer at a clean energy company. I want to show young athletes that scholarships exist at every level, and that engineering is one of the most valuable paths a student athlete can choose.`,
    },
    areas: [
      { category: 'Academic',             area: 'Mathematics' },
      { category: 'Academic',             area: 'Computer Science' },
      { category: 'Test Prep & Advising', area: 'College Selection' },
      { category: 'Test Prep & Advising', area: 'Financial Aid / Scholarships' },
      { category: 'Career & Life Skills', area: 'Time Management' },
    ],
    availability: { hours_per_week: 3, format: 'Video Call', timezone: 'America/Chicago' },
  },

  // ── 8 ─────────────────────────────────────────────────────────────────────
  {
    email:    'mentor.priya@bandb.test',
    password: 'devpass123',
    profile: {
      name:              'Priya Patel',
      hometown:          'Fremont',
      state:             'CA',
      gender:            'Female',
      ethnicity:         'Asian / Pacific Islander',
      sport:             'Volleyball',
      college:           'Stanford University',
      division:          'D1',
      years_active:      4,
      position:          'Outside Hitter',
      career_highlights: 'Two Pac-12 championships · All-Pac-12 junior and senior year · 3.8 GPA in CS',
      major:             'Computer Science',
      gpa_range:         '3.5–4.0',
      graduate_school:   null,
      current_job:       'Software Engineer',
      current_employer:  'Google',
      industry:          'Technology',
      current_city:      'Mountain View',
      current_state:     'CA',
      bio: `Playing outside hitter at Stanford was the most challenging and rewarding experience of my life. Our team won two Pac-12 championships while I majored in computer science with a 3.8 GPA—only possible with extreme time management and a culture that genuinely valued academics. I now work as a software engineer at Google on the Cloud infrastructure team. I love mentoring student athletes who want to pursue STEM careers, helping with computer science fundamentals, managing their schedules, and thinking through which colleges will set them up for both athletic and academic success.`,
    },
    areas: [
      { category: 'Academic',             area: 'Computer Science' },
      { category: 'Academic',             area: 'Mathematics' },
      { category: 'Academic',             area: 'Sciences' },
      { category: 'Test Prep & Advising', area: 'College Essays' },
      { category: 'Career & Life Skills', area: 'Time Management' },
      { category: 'Career & Life Skills', area: 'Career Exploration' },
    ],
    availability: { hours_per_week: 3, format: 'Video Call', timezone: 'America/Los_Angeles' },
  },

  // ── 9 ─────────────────────────────────────────────────────────────────────
  {
    email:    'mentor.isaiah@bandb.test',
    password: 'devpass123',
    profile: {
      name:              'Isaiah Brown',
      hometown:          'Washington',
      state:             'DC',
      gender:            'Male',
      ethnicity:         'Black / African American',
      sport:             'Track & Field',
      college:           'Morehouse College',
      division:          'D2',
      years_active:      4,
      position:          '110m Hurdles',
      career_highlights: 'Two-time SIAC champion · Three-time HBCU All-American · Graduated summa cum laude',
      major:             'Political Science',
      gpa_range:         '3.5–4.0',
      graduate_school:   'Howard University School of Law — J.D.',
      current_job:       'Civil Rights Attorney',
      current_employer:  'NAACP Legal Defense Fund',
      industry:          'Law',
      current_city:      'Washington',
      current_state:     'DC',
      bio: `I ran the 110m hurdles at Morehouse College, where I was a two-time SIAC champion and three-time All-American. Morehouse gave me a political consciousness and academic rigor that shaped who I am—I graduated summa cum laude and went on to Howard University Law School. I now practice civil rights law at the NAACP Legal Defense Fund. I mentor athletes interested in law, public service, or social justice, and I advocate for HBCU athletes who deserve the same opportunities as anyone else. I can help you craft college essays, navigate financial aid, and think through your future.`,
    },
    areas: [
      { category: 'Academic',             area: 'History' },
      { category: 'Academic',             area: 'English / Writing' },
      { category: 'Test Prep & Advising', area: 'College Essays' },
      { category: 'Test Prep & Advising', area: 'Financial Aid / Scholarships' },
      { category: 'Career & Life Skills', area: 'Career Exploration' },
    ],
    availability: { hours_per_week: 3, format: 'Video Call', timezone: 'America/New_York' },
  },

  // ── 10 ────────────────────────────────────────────────────────────────────
  {
    email:    'mentor.madison@bandb.test',
    password: 'devpass123',
    profile: {
      name:              'Madison Cooper',
      hometown:          'Nashville',
      state:             'TN',
      gender:            'Female',
      ethnicity:         'White / Caucasian',
      sport:             'Volleyball',
      college:           'Bellarmine University',
      division:          'D2',
      years_active:      4,
      position:          'Setter',
      career_highlights: 'Two-time All-Conference · Academic All-American · Clinical honors in nursing',
      major:             'Nursing',
      gpa_range:         '3.5–4.0',
      graduate_school:   null,
      current_job:       'Registered Nurse',
      current_employer:  'Vanderbilt University Medical Center',
      industry:          'Healthcare',
      current_city:      'Nashville',
      current_state:     'TN',
      bio: `I set for Bellarmine's Division II volleyball program for four years, earning All-Conference honors twice. My nursing major pushed me academically in ways I didn't expect, and the discipline I built through volleyball was exactly what carried me through clinical rotations. I'm now a registered nurse at Vanderbilt and still coach club volleyball on weekends. I mentor athletes interested in healthcare, and I love showing them how sport directly teaches the precision, composure under pressure, and teamwork that medical professionals need every single day.`,
    },
    areas: [
      { category: 'Academic',             area: 'Sciences' },
      { category: 'Athletic Development', area: 'Nutrition' },
      { category: 'Athletic Development', area: 'Athletic Training' },
      { category: 'Athletic Development', area: 'Mental Performance' },
      { category: 'Career & Life Skills', area: 'Time Management' },
    ],
    availability: { hours_per_week: 3, format: 'Any', timezone: 'America/Chicago' },
  },

  // ── 11 ────────────────────────────────────────────────────────────────────
  {
    email:    'mentor.carlos@bandb.test',
    password: 'devpass123',
    profile: {
      name:              'Carlos Mendoza',
      hometown:          'Miami',
      state:             'FL',
      gender:            'Male',
      ethnicity:         'Hispanic / Latino',
      sport:             'Baseball',
      college:           'University of Florida',
      division:          'D1',
      years_active:      4,
      position:          'Pitcher',
      career_highlights: 'SEC championship · Two-time All-SEC · Posted 2.81 career ERA',
      major:             'Finance',
      gpa_range:         '3.0–3.5',
      graduate_school:   'University of Florida — MBA',
      current_job:       'Investment Banker',
      current_employer:  'Goldman Sachs',
      industry:          'Finance',
      current_city:      'New York',
      current_state:     'NY',
      bio: `I pitched at the University of Florida, where we won an SEC championship and I earned two All-SEC selections. Baseball at D1 is a year-round commitment, and learning to manage that alongside a finance degree prepared me for the pace of investment banking. I earned my MBA at Florida and now work at Goldman Sachs in New York. I help athletes understand the financial landscape—especially NIL—and how to build a career from their platform. I also help pitchers and hitters create highlight packages that actually get noticed by college scouts.`,
    },
    areas: [
      { category: 'Career & Life Skills',  area: 'Financial Literacy' },
      { category: 'Career & Life Skills',  area: 'NIL Guidance' },
      { category: 'Career & Life Skills',  area: 'Resume / Interview Prep' },
      { category: 'Career & Life Skills',  area: 'Career Exploration' },
      { category: 'Athletic Development',  area: 'Highlight Tape' },
    ],
    availability: { hours_per_week: 1, format: 'Video Call', timezone: 'America/New_York' },
  },

  // ── 12 ────────────────────────────────────────────────────────────────────
  {
    email:    'mentor.charlotte@bandb.test',
    password: 'devpass123',
    profile: {
      name:              'Charlotte Davis',
      hometown:          'Greenwich',
      state:             'CT',
      gender:            'Female',
      ethnicity:         'White / Caucasian',
      sport:             'Tennis',
      college:           'Amherst College',
      division:          'D3',
      years_active:      4,
      position:          'Singles & Doubles',
      career_highlights: 'Three-time NESCAC champion · All-American twice · Graduated with honors in Economics',
      major:             'Economics',
      gpa_range:         '3.5–4.0',
      graduate_school:   null,
      current_job:       'Engagement Manager',
      current_employer:  'McKinsey & Company',
      industry:          'Consulting',
      current_city:      'New York',
      current_state:     'NY',
      bio: `I played singles and doubles tennis at Amherst College, a Division III liberal arts school where I was a three-time NESCAC champion. Choosing Amherst over larger programs was the right call—small classes, genuine professor relationships, and the freedom to pursue economics seriously without feeling like a second-class student. I graduated with honors, joined McKinsey as an analyst, and now manage client engagements. I mentor athletes navigating the balance between serious athletics and academics, and I'm especially passionate about helping athletes from underrepresented backgrounds access elite college opportunities.`,
    },
    areas: [
      { category: 'Career & Life Skills',  area: 'Career Exploration' },
      { category: 'Career & Life Skills',  area: 'Resume / Interview Prep' },
      { category: 'Career & Life Skills',  area: 'Financial Literacy' },
      { category: 'Career & Life Skills',  area: 'Time Management' },
      { category: 'Test Prep & Advising',  area: 'College Selection' },
      { category: 'Test Prep & Advising',  area: 'College Essays' },
    ],
    availability: { hours_per_week: 3, format: 'Video Call', timezone: 'America/New_York' },
  },

  // ── 13 ────────────────────────────────────────────────────────────────────
  {
    email:    'mentor.ryan@bandb.test',
    password: 'devpass123',
    profile: {
      name:              'Ryan O\'Brien',
      hometown:          'Baltimore',
      state:             'MD',
      gender:            'Male',
      ethnicity:         'Multiracial',
      sport:             'Lacrosse',
      college:           'University of Maryland',
      division:          'D1',
      years_active:      4,
      position:          'Midfielder',
      career_highlights: 'NCAA championship junior year · Two-time All-American · Two-time All-ACC',
      major:             'Marketing',
      gpa_range:         '3.0–3.5',
      graduate_school:   null,
      current_job:       'Brand Manager, Athlete Partnerships',
      current_employer:  'Under Armour',
      industry:          'Entertainment / Media',
      current_city:      'Baltimore',
      current_state:     'MD',
      bio: `I played midfielder for Maryland lacrosse—one of the most storied programs in the country—winning an NCAA championship my junior year and earning two All-American honors. Playing at that level taught me about brand, identity, and the value of your platform. I majored in marketing and now manage athlete partnerships at Under Armour. I love helping athletes build their personal brand and NIL strategy before they even arrive on campus, and I specialize in helping recruits put together highlight tape that actually gets noticed by D1 programs.`,
    },
    areas: [
      { category: 'Career & Life Skills',  area: 'NIL Guidance' },
      { category: 'Career & Life Skills',  area: 'Career Exploration' },
      { category: 'Career & Life Skills',  area: 'Resume / Interview Prep' },
      { category: 'Athletic Development',  area: 'Highlight Tape' },
      { category: 'Athletic Development',  area: 'Film Study' },
    ],
    availability: { hours_per_week: 3, format: 'Video Call', timezone: 'America/New_York' },
  },

  // ── 14 ────────────────────────────────────────────────────────────────────
  {
    email:    'mentor.brianna@bandb.test',
    password: 'devpass123',
    profile: {
      name:              'Brianna Johnson',
      hometown:          'Philadelphia',
      state:             'PA',
      gender:            'Female',
      ethnicity:         'Black / African American',
      sport:             'Lacrosse',
      college:           'Middlebury College',
      division:          'D3',
      years_active:      4,
      position:          'Attack',
      career_highlights: 'Two-time All-NESCAC · Thesis award in Environmental Science · Study abroad in Costa Rica',
      major:             'Environmental Science',
      gpa_range:         '3.5–4.0',
      graduate_school:   'Yale School of the Environment — M.E.Sc.',
      current_job:       'Environmental Policy Analyst',
      current_employer:  'Environmental Defense Fund',
      industry:          'Government / Nonprofit',
      current_city:      'Washington',
      current_state:     'DC',
      bio: `I played attack for Middlebury lacrosse in Vermont, a Division III program that takes both athletics and academics seriously. Middlebury gave me research opportunities and a study abroad semester in Costa Rica that a larger school couldn't have offered. I studied environmental science, earned a master's at Yale's School of the Environment, and now work as an environmental policy analyst in D.C. I mentor athletes thinking about small liberal arts colleges or environmental careers—and I especially love helping students craft authentic, specific college essays that stand out.`,
    },
    areas: [
      { category: 'Academic',             area: 'Sciences' },
      { category: 'Academic',             area: 'English / Writing' },
      { category: 'Test Prep & Advising', area: 'College Essays' },
      { category: 'Test Prep & Advising', area: 'College Selection' },
      { category: 'Test Prep & Advising', area: 'Financial Aid / Scholarships' },
    ],
    availability: { hours_per_week: 3, format: 'Video Call', timezone: 'America/New_York' },
  },

  // ── 15 ────────────────────────────────────────────────────────────────────
  {
    email:    'mentor.tyler@bandb.test',
    password: 'devpass123',
    profile: {
      name:              'Tyler Nguyen',
      hometown:          'San Jose',
      state:             'CA',
      gender:            'Male',
      ethnicity:         'Asian / Pacific Islander',
      sport:             'Swimming',
      college:           'University of Michigan',
      division:          'D1',
      years_active:      4,
      position:          'Backstroke / Individual Medley',
      career_highlights: 'Four-time All-American · School record holder (200 IM) · 3.7 GPA in Biomedical Engineering',
      major:             'Biomedical Engineering',
      gpa_range:         '3.5–4.0',
      graduate_school:   'MIT — PhD, Biomedical Engineering (in progress)',
      current_job:       'PhD Researcher & Medical Device Engineer',
      current_employer:  'MIT / Medtronic (part-time)',
      industry:          'Healthcare',
      current_city:      'Cambridge',
      current_state:     'MA',
      bio: `I swam backstroke and individual medley at the University of Michigan, earning four All-American honors and setting a school record in the 200 IM. Michigan pushed me academically as much as athletically—I studied biomedical engineering with a 3.7 GPA and am now completing a PhD at MIT. Swimming at a high level while pursuing STEM is absolutely possible, and I want to help the next generation prove it. I mentor athletes interested in engineering or pre-med paths and help them build the study habits and time management systems to do both well.`,
    },
    areas: [
      { category: 'Academic',             area: 'Sciences' },
      { category: 'Academic',             area: 'Mathematics' },
      { category: 'Academic',             area: 'Computer Science' },
      { category: 'Test Prep & Advising', area: 'SAT / ACT Prep' },
      { category: 'Career & Life Skills', area: 'Time Management' },
    ],
    availability: { hours_per_week: 1, format: 'Video Call', timezone: 'America/New_York' },
  },

  // ── 16 ────────────────────────────────────────────────────────────────────
  {
    email:    'mentor.jordan@bandb.test',
    password: 'devpass123',
    profile: {
      name:              'Jordan Mitchell',
      hometown:          'Detroit',
      state:             'MI',
      gender:            'Male',
      ethnicity:         'Multiracial',
      sport:             'Basketball',
      college:           'Michigan State University',
      division:          'D1',
      years_active:      4,
      position:          'Small Forward',
      career_highlights: 'Big Ten tournament champion · All-Big Ten second team · One season pro in Germany',
      major:             'Sports Administration',
      gpa_range:         '3.0–3.5',
      graduate_school:   null,
      current_job:       'Player Development Coordinator',
      current_employer:  'NBA Franchise',
      industry:          'Sports / Athletics',
      current_city:      'Detroit',
      current_state:     'MI',
      bio: `I played small forward at Michigan State for four years, winning a Big Ten tournament championship and earning All-Big Ten honors. I studied sports administration and always knew I'd work in basketball. I spent one year playing professionally in Germany before transitioning into an NBA team's player development operation. I mentor athletes who want to play at the next level—breaking down film, building a highlights package, mental performance—and those who want to work in professional sports after their playing days are over.`,
    },
    areas: [
      { category: 'Athletic Development',  area: 'Sport-Specific Skills' },
      { category: 'Athletic Development',  area: 'Film Study' },
      { category: 'Athletic Development',  area: 'Highlight Tape' },
      { category: 'Athletic Development',  area: 'Mental Performance' },
      { category: 'Career & Life Skills',  area: 'NIL Guidance' },
      { category: 'Career & Life Skills',  area: 'Career Exploration' },
    ],
    availability: { hours_per_week: 3, format: 'Video Call', timezone: 'America/New_York' },
  },

  // ── 17 ────────────────────────────────────────────────────────────────────
  {
    email:    'mentor.jake@bandb.test',
    password: 'devpass123',
    profile: {
      name:              'Jake Kowalski',
      hometown:          'Milwaukee',
      state:             'WI',
      gender:            'Male',
      ethnicity:         'White / Caucasian',
      sport:             'Baseball',
      college:           'Pomona College',
      division:          'D3',
      years_active:      4,
      position:          'Catcher',
      career_highlights: 'Two-time All-SCIAC · Thesis on statistical modeling in baseball · 3.9 GPA',
      major:             'Mathematics',
      gpa_range:         '3.5–4.0',
      graduate_school:   null,
      current_job:       'Senior Data Scientist',
      current_employer:  'Spotify',
      industry:          'Technology',
      current_city:      'New York',
      current_state:     'NY',
      bio: `I caught for Pomona College baseball in the Claremont Colleges system—a small, academically rigorous Division III environment where I could take mathematics seriously while competing meaningfully. I graduated, joined a tech company as a junior analyst, and transitioned into data science. I now build recommendation systems at Spotify. I mentor athletes who are interested in math, statistics, or data careers, and I'm especially passionate about helping them understand that D3 can be the smartest academic choice they make, not a fallback.`,
    },
    areas: [
      { category: 'Academic',             area: 'Mathematics' },
      { category: 'Academic',             area: 'Computer Science' },
      { category: 'Career & Life Skills', area: 'Financial Literacy' },
      { category: 'Career & Life Skills', area: 'Time Management' },
      { category: 'Test Prep & Advising', area: 'College Selection' },
    ],
    availability: { hours_per_week: 3, format: 'Video Call', timezone: 'America/New_York' },
  },

  // ── 18 ────────────────────────────────────────────────────────────────────
  {
    email:    'mentor.destiny@bandb.test',
    password: 'devpass123',
    profile: {
      name:              'Destiny Flowers',
      hometown:          'Atlanta',
      state:             'GA',
      gender:            'Female',
      ethnicity:         'Black / African American',
      sport:             'Softball',
      college:           'Spelman College',
      division:          'NAIA',
      years_active:      4,
      position:          'Pitcher / Outfield',
      career_highlights: 'SIAC All-Conference three times · Team MVP senior year · Graduated with honors',
      major:             'Education',
      gpa_range:         '3.5–4.0',
      graduate_school:   null,
      current_job:       'High School Teacher & Softball Coach',
      current_employer:  'Atlanta Public Schools',
      industry:          'Education',
      current_city:      'Atlanta',
      current_state:     'GA',
      bio: `I played softball at Spelman College, a historically Black women's college in Atlanta that changed my life. Athletics at an HBCU is a different experience—the community, the culture, the sisterhood—and I would choose it again in a heartbeat. I majored in education and became a high school math teacher and softball coach. I believe athletes who struggle academically just haven't found the right way into the material yet, and I pride myself on making math, writing, and standardized tests approachable. I especially love helping first-generation college athletes and their families navigate financial aid.`,
    },
    areas: [
      { category: 'Academic',             area: 'Mathematics' },
      { category: 'Academic',             area: 'English / Writing' },
      { category: 'Academic',             area: 'History' },
      { category: 'Academic',             area: 'Foreign Languages' },
      { category: 'Test Prep & Advising', area: 'SAT / ACT Prep' },
      { category: 'Test Prep & Advising', area: 'Financial Aid / Scholarships' },
    ],
    availability: { hours_per_week: 6, format: 'Any', timezone: 'America/New_York' },
  },

  // ── 19 ────────────────────────────────────────────────────────────────────
  {
    email:    'mentor.zoe@bandb.test',
    password: 'devpass123',
    profile: {
      name:              'Zoe Kim',
      hometown:          'Seattle',
      state:             'WA',
      gender:            'Female',
      ethnicity:         'Asian / Pacific Islander',
      sport:             'Track & Field',
      college:           'Seattle Pacific University',
      division:          'D2',
      years_active:      4,
      position:          '5000m / 10000m',
      career_highlights: 'Three-time NCAA DII All-American · Team captain · Course record at conference championships',
      major:             'Nutrition & Dietetics',
      gpa_range:         '3.5–4.0',
      graduate_school:   null,
      current_job:       'Registered Dietitian',
      current_employer:  'Seattle Children\'s Hospital',
      industry:          'Healthcare',
      current_city:      'Seattle',
      current_state:     'WA',
      bio: `I ran the 5000m and 10000m at Seattle Pacific University in Division II, earning three NCAA DII All-American honors as team captain. Long-distance running teaches a different kind of mental endurance—you learn to stay present and keep going when everything says stop. I studied nutrition and dietetics, became a registered dietitian, and now work with endurance athletes and youth sports programs in the Pacific Northwest. I help athletes across all sports fuel their bodies correctly, recover properly, and build the mental toughness that separates good from great.`,
    },
    areas: [
      { category: 'Athletic Development', area: 'Nutrition' },
      { category: 'Athletic Development', area: 'Athletic Training' },
      { category: 'Athletic Development', area: 'Strength & Conditioning' },
      { category: 'Athletic Development', area: 'Mental Performance' },
      { category: 'Career & Life Skills', area: 'Time Management' },
    ],
    availability: { hours_per_week: 3, format: 'Video Call', timezone: 'America/Los_Angeles' },
  },

  // ── 20 ────────────────────────────────────────────────────────────────────
  {
    email:    'mentor.antonio@bandb.test',
    password: 'devpass123',
    profile: {
      name:              'Antonio Reyes',
      hometown:          'Daytona Beach',
      state:             'FL',
      gender:            'Male',
      ethnicity:         'Hispanic / Latino',
      sport:             'Football',
      college:           'Bethune-Cookman University',
      division:          'NAIA',
      years_active:      4,
      position:          'Placekicker / Punter',
      career_highlights: 'Three-time MEAC All-Conference · 88% career field goal percentage · Bilingual (English/Spanish)',
      major:             'Business & Entrepreneurship',
      gpa_range:         '3.0–3.5',
      graduate_school:   null,
      current_job:       'Founder',
      current_employer:  'Reyes Sports & Tutoring Academy',
      industry:          'Education',
      current_city:      'Orlando',
      current_state:     'FL',
      bio: `I played kicker and punter at Bethune-Cookman University, an HBCU in Daytona Beach, where I was a three-time MEAC All-Conference selection. Being a specialist at a smaller school taught me that value isn't measured in prestige—it's measured in how you prepare. I studied business and entrepreneurship, then started two companies: a sports training academy and a bilingual tutoring service for Spanish-speaking families. I love mentoring athletes who want to become entrepreneurs, and I'm especially passionate about helping Spanish-speaking athletes navigate the college and career landscape with confidence.`,
    },
    areas: [
      { category: 'Career & Life Skills', area: 'Financial Literacy' },
      { category: 'Career & Life Skills', area: 'NIL Guidance' },
      { category: 'Career & Life Skills', area: 'Career Exploration' },
      { category: 'Career & Life Skills', area: 'Resume / Interview Prep' },
      { category: 'Career & Life Skills', area: 'Time Management' },
      { category: 'Academic',             area: 'Foreign Languages' },
    ],
    availability: { hours_per_week: 3, format: 'Any', timezone: 'America/New_York' },
  },
]
