-- =============================================================================
-- Switch embeddings from OpenAI text-embedding-3-small (1536 dims)
-- to Supabase gte-small (384 dims). No external API key required.
-- =============================================================================

-- Drop match_mentors first — it has a vector(1536) parameter that must change.
drop function if exists public.match_mentors;

-- Existing embeddings are 1536-dim and cannot be cast to 384-dim.
-- They will be regenerated by running: npm run embed:mentors
truncate table public.mentor_embeddings;

-- Resize the column.
alter table public.mentor_embeddings
  alter column embedding type vector(384);

-- Recreate match_mentors with the new dimension.
create or replace function public.match_mentors(
  query_embedding vector(384),
  candidate_ids   uuid[],
  match_count     int default 3
)
returns table (mentor_id uuid, similarity numeric)
language sql stable
security definer
set search_path = public
as $$
  select
    me.mentor_id,
    (1 - (me.embedding <=> query_embedding))::numeric as similarity
  from public.mentor_embeddings me
  where me.mentor_id = any(candidate_ids)
  order by me.embedding <=> query_embedding
  limit match_count;
$$;

revoke execute on function public.match_mentors from public, anon, authenticated;
grant  execute on function public.match_mentors to service_role;
